import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "_provider/themeProvider";
import ThemeToggle from "_ui/themeToggle";
import { iranSans } from "_ui/fonts";
import NavBar from "@/_ui/header/navBar";
import { navs, services } from "@/_lib/navBars";
import logo from "@/_assets/images/varzesh3.svg";
import Services from "@/_ui/header/services";
import Footer1 from "@/_ui/footer/footer1";
import Footer2 from "@/_ui/footer/footer2";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => {
  return (
    <html lang="fa" dir="rtl" className={`${iranSans.variable} antialiased`} suppressHydrationWarning>
      <body className={`bg-[#373737] light:bg-[#d9d9d9] text-white light:text-black font-iranSans`}>
        <ThemeProvider>
          <header className={``}>
            <Services/>
            <NavBar navs={navs} logo={logo} anotherNav={services}/>
          </header>
          {children}
          <footer className={`py-10.5 flex flex-col gap-6 bg-[#18242f]`}>
            <Footer1/>
            <Footer2/>
          </footer>
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
