import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "_provider/themeProvider";
import ThemeToggle from "_ui/themeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({children}: LayoutProps<'/'>) => {
  return (
    <html lang="en" className={`antialiased`} suppressHydrationWarning>
      <body className={`bg-black light:bg-white text-white light:text-black transition-all duration-500`}>
        <ThemeProvider>
          {children}
          <ThemeToggle/>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;